### ISSUE TITLE
C++11 standard requested but CXX11 is not defined

### ISSUE THREAD

**Issue by rhobis** [nanxstats/hdnom#5]
Hi,
when trying to download the developer version on R 3.4 the following error is returned:

```
Error in .shlib_internal(args) : 
  C++11 standard requested but CXX11 is not define
```

**Comment by nanxstats** [comment]
Hi @rhobis ,

-this seems to be related to a recent C++ support issue in R 3.4, see

https://github.com/rstudio/httpuv/issues/79
https://github.com/jeroen/protolite/issues/5
https://github.com/rstudio/httpuv/issues/82
http://r.789695.n4.nabble.com/R-3-4-has-broken-C-11-support-td4732692.html

Some dependencies of hdnom might use Rcpp, thus the problem. However, there is not much I can do. As a possible workaround, I would suggest installing the binary versions (if using Windows or Mac) of the packages from CRAN, then install the dev version of hdnom from GitHub (which doesn't require the C++ environment).

I'm also planning to release a new version of this package to CRAN today.

Thanks,
-Nan
