### ISSUE TITLE
Error in UseMethod("validate") : 

### ISSUE THREAD

**Issue by JianGuoZhou3** [nanxstats/hdnom#8]
@nanxstats thanks for your package.
i have some questions.
> val_int <- validate(
+     x, time, event,
+     model.type = "aenet",
+     alpha = alpha, lambda = lambda, pen.factor = adapen,
+     method = "bootstrap", boot.times = 10,
+     tauc.type = "UNO", tauc.time = seq(1, 5, 0.5) * 365,
+     seed = 42, trace = FALSE
+   )
Error in UseMethod("validate") : 
  no applicable method for 'validate' applied to an object of class "c('matrix', 'double', 'numeric')"

**Comment by nanxstats** [comment]
@jianguozhouzunyimedicaluniversity -please try `hdnom::validate` since it might have namespace conflicts with `shiny::validate`.

**Comment by JianGuoZhou3** [comment]
Hello nan,
I have a question of HR.
cal.int.logrank = logrank_test(cal.int_lasso)
cal.int.logrank
cal.int.logrank$pval

Call:
survdiff(formula = formula("Surv(time, event) ~ grp"))

n=510, 1 observation deleted due to missingness.

        N Observed Expected (O-E)^2/E (O-E)^2/V
grp=1 255      133     78.9      37.1      68.4
grp=2 255       41     95.1      30.8      68.4

 Chisq= 68.4  on 1 degrees of freedom, p= <2e-16 
[1] 1.365953e-16

ncvreg_basesurv(time, event, cal.int_lasso, times.eval = NULL, centered = FALSE)
BUT DONT WORK



 Show Traceback <>
Error: object 'hdnom' not found

High-Dimensional Cox Model External Validation Object
Model type: lasso 
Time-dependent AUC type: UNO 
Evaluation time points for tAUC: 182.5 365 547.5 730 912.5 1095 1277.5 1460 1642.5 1825Time-Dependent AUC Summary at Evaluation Time Points
        182.5       365     547.5      730     912.5     1095   1277.5      1460   1642.5
AUC 0.5746772 0.6488238 0.6511497 0.649257 0.6736041 0.678176 0.687886 0.6897965 0.700109
         1825
AUC 0.7246998
        182.5       365     547.5      730     912.5     1095   1277.5      1460   1642.5
AUC 0.5746772 0.6488238 0.6511497 0.649257 0.6736041 0.678176 0.687886 0.6897965 0.700109
         1825
AUC 0.7246998
R Console



Error in hdcox.aenet(x, y, nfolds = 10, rule = "lambda.1se", seed = c(5,  : 
  could not find function "hdcox.aenet"


High-Dimensional Cox Model Validation Object
Random seed: 42 
Validation method: bootstrap
Bootstrap samples: 2000 
Model type: lasso 
glmnet model alpha: 0.05 
glmnet model lambda: 0.07872174 
glmnet model penalty factor: specified
Time-dependent AUC type: UNO 
Evaluation time points for tAUC: 365 547.5 730 912.5 1095 1277.5 1460 1642.5 1825Time-Dependent AUC Summary at Evaluation Time Points
               365     547.5       730     912.5      1095    1277.5      1460    1642.5
Mean     0.7562497 0.7410770 0.7412096 0.7229640 0.7515909 0.7603689 0.7657267 0.7666966
Min      0.6606648 0.6780851 0.6866201 0.6822605 0.7138467 0.7235209 0.7328998 0.7408280
0.25 Qt. 0.7462427 0.7318032 0.7317429 0.7155564 0.7456286 0.7566830 0.7621093 0.7636615
Median   0.7590576 0.7434713 0.7427357 0.7235393 0.7523726 0.7611868 0.7666013 0.7672540
0.75 Qt. 0.7690566 0.7527866 0.7520526 0.7308922 0.7586606 0.7648097 0.7705407 0.7702722
Max      0.7918868 0.7748952 0.7796766 0.7540440 0.7740406 0.7748450 0.7812699 0.7796524
              1825
Mean     0.7632895
Min      0.7363868
0.25 Qt. 0.7599443
Median   0.7635705
0.75 Qt. 0.7670344
Max      0.7810796
               365     547.5       730     912.5      1095    1277.5      1460    1642.5
Mean     0.7562497 0.7410770 0.7412096 0.7229640 0.7515909 0.7603689 0.7657267 0.7666966
Min      0.6606648 0.6780851 0.6866201 0.6822605 0.7138467 0.7235209 0.7328998 0.7408280
0.25 Qt. 0.7462427 0.7318032 0.7317429 0.7155564 0.7456286 0.7566830 0.7621093 0.7636615
Median   0.7590576 0.7434713 0.7427357 0.7235393 0.7523726 0.7611868 0.7666013 0.7672540
0.75 Qt. 0.7690566 0.7527866 0.7520526 0.7308922 0.7586606 0.7648097 0.7705407 0.7702722
Max      0.7918868 0.7748952 0.7796766 0.7540440 0.7740406 0.7748450 0.7812699 0.7796524
              1825
Mean     0.7632895
Min      0.7363868
0.25 Qt. 0.7599443
Median   0.7635705
0.75 Qt. 0.7670344
Max      0.7810796
R Console

High-Dimensional Cox Model Validation Object
Random seed: 42 
Validation method: bootstrap
Bootstrap samples: 2000 
Model type: lasso 
glmnet model alpha: 0.05 
glmnet model lambda: 0.07872174 
glmnet model penalty factor: specified
Time-dependent AUC type: UNO 
Evaluation time points for tAUC: 365 547.5 730 912.5 1095 1277.5 1460 1642.5 1825Time-Dependent AUC Summary at Evaluation Time Points
               365     547.5       730     912.5      1095    1277.5      1460    1642.5
Mean     0.7562497 0.7410770 0.7412096 0.7229640 0.7515909 0.7603689 0.7657267 0.7666966
Min      0.6606648 0.6780851 0.6866201 0.6822605 0.7138467 0.7235209 0.7328998 0.7408280
0.25 Qt. 0.7462427 0.7318032 0.7317429 0.7155564 0.7456286 0.7566830 0.7621093 0.7636615
Median   0.7590576 0.7434713 0.7427357 0.7235393 0.7523726 0.7611868 0.7666013 0.7672540
0.75 Qt. 0.7690566 0.7527866 0.7520526 0.7308922 0.7586606 0.7648097 0.7705407 0.7702722
Max      0.7918868 0.7748952 0.7796766 0.7540440 0.7740406 0.7748450 0.7812699 0.7796524
              1825
Mean     0.7632895
Min      0.7363868
0.25 Qt. 0.7599443
Median   0.7635705
0.75 Qt. 0.7670344
Max      0.7810796
               365     547.5       730     912.5      1095    1277.5      1460    1642.5
Mean     0.7562497 0.7410770 0.7412096 0.7229640 0.7515909 0.7603689 0.7657267 0.7666966
Min      0.6606648 0.6780851 0.6866201 0.6822605 0.7138467 0.7235209 0.7328998 0.7408280
0.25 Qt. 0.7462427 0.7318032 0.7317429 0.7155564 0.7456286 0.7566830 0.7621093 0.7636615
Median   0.7590576 0.7434713 0.7427357 0.7235393 0.7523726 0.7611868 0.7666013 0.7672540
0.75 Qt. 0.7690566 0.7527866 0.7520526 0.7308922 0.7586606 0.7648097 0.7705407 0.7702722
Max      0.7918868 0.7748952 0.7796766 0.7540440 0.7740406 0.7748450 0.7812699 0.7796524
              1825
Mean     0.7632895
Min      0.7363868
0.25 Qt. 0.7599443
Median   0.7635705
0.75 Qt. 0.7670344
Max      0.7810796

High-Dimensional Cox Model Calibration Object
Random seed: 42 
Calibration method: k-fold cross-validation
Cross-validation folds: 10 
Model type: lasso 
glmnet model alpha: 0.05 
glmnet model lambda: 0.07872174 
glmnet model penalty factor: specified
Calibration time point: 1825 
Number of groups formed for calibration: 2 
  Calibration Summary Table
  Predicted  Observed Lower 95% Upper 95%
1 0.5079312 0.4988368 0.4387031 0.5672131
2 0.8609773 0.8365966 0.7905943 0.8852756
R Console

High-Dimensional Cox Model Calibration Object
Random seed: 42 
Calibration method: k-fold cross-validation
Cross-validation folds: 10 
Model type: lasso 
glmnet model alpha: 0.05 
glmnet model lambda: 0.07872174 
glmnet model penalty factor: specified
Calibration time point: 1825 
Number of groups formed for calibration: 2 
  Calibration Summary Table
  Predicted  Observed Lower 95% Upper 95%
1 0.5079312 0.4988368 0.4387031 0.5672131
2 0.8609773 0.8365966 0.7905943 0.8852756

High-Dimensional Cox Model External Calibration Object
Model type: lasso 
Calibration time point: 1825 
Number of groups formed for calibration: 2 
  External Calibration Summary Table
  Predicted  Observed Lower 95% Upper 95%
1 0.5654510 0.5638794 0.4839030 0.6570739
2 0.7797965 0.9453829 0.8947434 0.9988884
R Console
